# https://taskfile.dev

version: "3"

env:
  PRESENTATION: how-to-deal-with-toxic-people.md
  SLIDES_URL: https://foosel.github.io/ep2025/

tasks:
  qrcodes:
    desc: Updates the QR Codes
    cmds:
      - npx qrcode -o img/qrcode-slides.png -w 1000 "{{ .SLIDES_URL }}"
      - npx qrcode -o img/qrcode-contract.png -w 400 "https://snarky.ca/the-social-contract-of-open-source"

  build:
    desc: Builds the presentation
    cmds:
      - task: qrcodes
      - mkslides build {{ .PRESENTATION }}
  
  serve:
    desc: Serve the presentation
    cmds:
      - mkslides serve -a 0.0.0.0:8000 {{ .PRESENTATION }}
